// <auto-generated />
namespace MyStoreDesktop.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class addedQrCode : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addedQrCode));
        
        string IMigrationMetadata.Id
        {
            get { return "202511070808175_addedQrCode"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
